name: quest
version: 0.1
main: taewookim562.main
description: 마인크래프트 서버내에 퀘스트를 만들어보세요!
authors: taewookim562
website: https://github.com/catking562/minecraft-plugins-quest.git

commands:
  퀘스트:
    description: 퀘스트 기본 명령어
    aliases: [quest]
    permission: quest.user
  퀘스트설정:
    description: 퀘스트를 만들고, 설정하고, 관리할 수 있는 명령어
    aliases: [questoption]
    permission: quest.admin
  퀘스트관리:
    description: 플레이어의 퀘스트를 관리할 수 있습니다.
    aliases: [questmanager]
    permission: quest.admin
    
permissions:
  quest.*:
    description: quest all permissions
    default: op
    children:
      quest.user: true
      quest.admin: true
  quest.user:
    description: quest user permissios
    default: true
  quest.admin:
    description: quest admin permissions
    default: true
    children:
      quest.user: true